name: Unit Tests

on:
  push:
  pull_request:
    branches: ['main']

env:
  BUILD_TYPE: Release

jobs:
  run_unit_tests:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure CMake
        run: cmake --log-level=VERBOSE -B "${{ github.workspace }}/build" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DENABLE_TESTING=ON

      - name: Build project
        run: cmake --log-level=VERBOSE --build "${{ github.workspace }}/build" --config ${{ env.BUILD_TYPE }}

      - name: Run unit tests
        run: ctest -C ${{ env.BUILD_TYPE }} --test-dir "${{ github.workspace }}/build/tests"